/**
 * Имена переменных в примерах — по-русски.
 *
 * Сцены пишутся один раз, по-английски: это настоящие программы, они гоняются тестами,
 * и держать две копии значило бы чинить каждую находку дважды. На русскую страницу та же
 * сцена приезжает с переписанными именами — как если бы её набрал русскоязычный автор.
 *
 * Переписываются только **имена переменных и строковые литералы**. Сам язык не трогается:
 * `sensor`, `@copper`, `jump` и числа остаются как были. Поэтому английское имя здесь
 * не может совпадать ни со словом языка, ни с латинским именем, которое в русской версии
 * остаётся латинским (`x`, `a`, `dx`): иначе перевод задел бы и его. Это держит тест.
 */

/** Имена переменных: английское имя из сцены — русское имя для страницы. */
export const NAMES = {
    // Основы: значения, имена, пустота
    stock: 'запас',
    Stock: 'Запас',
    stok: 'запс',
    spend: 'расход',
    limit: 'предел',
    total: 'итог',
    doubled: 'удвоено',
    copy: 'копия',
    number: 'число',
    text: 'текст',
    item: 'предмет',
    itemPlusOne: 'объектПлюсОдин',
    empty: 'пусто',
    blank: 'пустое',
    caption: 'надпись',
    value: 'значение',
    code: 'код',
    row: 'строка',
    column: 'столбец',

    // Арифметика и числа
    sum: 'сумма',
    difference: 'разность',
    product: 'произведение',
    quotient: 'частное',
    rest: 'остаток',
    gap: 'разница',
    share: 'доля',
    fraction: 'дробь',
    fractional: 'дробный',
    whole: 'целое',
    negative: 'отрицательный',
    almost: 'почти',
    exact: 'точно',
    withEpsilon: 'сДопуском',
    strict: 'строго',
    same: 'равно',
    both: 'оба',
    either: 'обе',
    flipped: 'инверт',
    mask: 'маска',
    shift: 'сдвиг',
    sign: 'знак',
    unsigned: 'беззнак',
    bitwise: 'побитовое',
    logical: 'логическое',
    lostBit: 'безЕдиницы',
    check: 'проверка',
    packed: 'упаковано',
    back: 'обратно',
    backX: 'обратноX',
    backY: 'обратноY',
    step: 'шаг',
    count: 'счёт',
    loops: 'итераций',
    loopsPerTick: 'итерацийЗаТик',
    idle: 'холостых',
    fired: 'сработало',
    deadline: 'срок',
    previous: 'прежний',
    changed: 'другой',
    swaps: 'смен',
    binds: 'привязок',
    wrapped: 'перебор',
    gone: 'негоден',
    done: 'сделано',
    ready: 'готово',
    skipped: 'пропущено',
    afterStop: 'послеСтопа',

    // Сравнения из урока про логику
    copperIsCopper: 'медьРавнаМеди',
    copperIsLead: 'медьРавнаСвинцу',
    blankIsZero: 'пустоеРавноНулю',
    blankStrictly: 'пустоеСтрого',
    unset: 'безЗначения',
    byZero: 'наНоль',
    atLeastOne: 'хотяБы',
    withOne: 'сОдной',

    // Время
    ticks: 'тики',
    seconds: 'секунды',
    minutes: 'минуты',
    millis: 'миллисекунды',
    fromTicks: 'изТиков',
    current: 'текущее',
    frames: 'показов',
    samples: 'снимков',

    // Память и связи
    address: 'адрес',
    cells: 'ячейки',
    cellSize: 'памятьЯчейки',
    routerSize: 'памятьМаршрута',
    block: 'блок',
    building: 'здание',
    building2: 'здание2',
    first: 'первый',
    second: 'второй',
    third: 'третий',
    fourth: 'четвёртый',
    firstOne: 'первая',
    secondOne: 'вторая',
    thirdOne: 'третья',
    firstText: 'первое',
    secondText: 'второе',
    fresh: 'новый',
    index: 'номер',
    graphiteId: 'номерГрафита',
    firstItem: 'первыйПредмет',
    firstLiquid: 'перваяЖидкость',
    firstUnit: 'первыйЮнит',
    pastEnd: 'заГраницей',
    itemCount: 'предметов',
    best: 'лучшее',
    what: 'чего',
    amount: 'сколько',
    howMany: 'сколькоБрать',
    everything: 'всего',
    enough: 'хватает',
    low: 'мало',
    plenty: 'много',
    left: 'осталось',

    // Содержимое складов
    copper: 'медь',
    copperLeft: 'меди',
    leadLeft: 'свинца',
    silicon: 'кремний',
    water: 'вода',
    copperInCore: 'медьВЯдре',
    copperInStore: 'медиНаСкладе',
    inStore: 'вСкладе',
    store: 'склад',
    storeX: 'складX',
    storeY: 'складY',
    core: 'ядро',
    storeFound: 'естьСклад',
    enemyStore: 'чужойСклад',
    delivered: 'привезено',
    give: 'выдать',

    // Блоки и настройка
    setting: 'настройка',
    on: 'включено',
    switched: 'включили',
    running: 'работает',
    mineRuns: 'свойРаботает',
    theirsRuns: 'чужойРаботает',
    mine: 'свой',
    theirs: 'чужой',
    ours: 'своя',
    enemys: 'вражья',
    oursX: 'свояX',
    oursY: 'свояY',
    ourOwn: 'своих',
    ourBuildings: 'своихЗданий',
    ourUnits: 'своихЮнитов',
    theirUnits: 'чужихЮнитов',
    enemies: 'врагов',
    turrets: 'турелей',
    commands: 'команд',
    team: 'команда',
    wall: 'стена',
    floor: 'пол',
    ore: 'руда',
    noOre: 'безРуды',
    oreX: 'рудаX',
    oreY: 'рудаY',
    placed: 'поставил',
    wasPlaced: 'поставили',
    wherePlaced: 'гдеПоставили',
    sameNumbers: 'поТемЖеЧислам',
    removed: 'снесли',
    blown: 'взорвали',
    burned: 'подожгли',
    lifted: 'подняли',
    found: 'нашлось',
    wasFound: 'найдено',
    needed: 'нужен',
    need: 'нужно',

    // Юниты
    unit: 'юнит',
    unitCount: 'юнитов',
    own: 'мой',
    sameOne: 'тотЖе',
    dead: 'мёртв',
    alive: 'живых',
    tough: 'живучий',
    health: 'здоровье',
    turretHealth: 'здоровьеТурели',
    nearHealth: 'ближнееЗдоровье',
    weakHealth: 'слабоеЗдоровье',
    kind: 'тип',
    firstKind: 'типПервого',
    newKind: 'типНового',
    tag: 'метка',
    tagged: 'помечено',
    lastTag: 'последний',
    cargo: 'груз',
    slots: 'мест',
    mining: 'копает',
    arrived: 'прибыл',
    reached: 'дошли',
    target: 'куда',
    flies: 'летит',
    flying: 'летящий',
    speed: 'скорость',
    boosted: 'разогнанная',
    ctrl: 'кем',
    who: 'кто',
    whoIsIt: 'ктоЭто',
    myself: 'яСам',
    whoseDagger: 'чейКинжал',
    ordered: 'отдал',
    roll: 'кубик',
    throw: 'бросок',

    // Поиск и радар
    near: 'ближний',
    far: 'дальний',
    weakest: 'слабый',
    closer: 'ближе',
    away: 'далеко',
    beside: 'рядом',
    range: 'дальность',
    distance: 'расстояние',
    inBox: 'вПрямоугольнике',
    enemyFound: 'естьВраг',
    allyFound: 'естьСвоя',
    enemyX: 'врагX',
    enemyY: 'врагY',
    damaged: 'битый',
    damagedX: 'битыйX',
    damagedY: 'битыйY',
    nearX: 'xБлижнего',
    farX: 'xДальнего',
    heldX: 'xСкованного',
    freeX: 'xСвободного',
    missX: 'нетX',
    missY: 'нетY',
    titaniumFound: 'титанЕсть',
    aim: 'цель',
    shooting: 'стреляет',
    ammo: 'патронов',
    shots: 'выстрелов',
    shot: 'пуля',
    facing: 'поворот',
    angle: 'угол',
    diagonal: 'диагональ',
    full: 'полное',
    up: 'вверх',
    down: 'вниз',
    behind: 'назад',
    after: 'после',
    here: 'тут',
    self: 'сам',

    // Цвет и рисование
    colour: 'цвет',
    red: 'красный',
    blue: 'голубой',
    R: 'кр',
    G: 'зел',
    B: 'син',
    A: 'прозр',
    alarm: 'тревога',
    calm: 'покой',

    // Мир и погода
    storm: 'буря',
    rain: 'дождь',
    height: 'высота',
    failure: 'ошибка',
    always: 'всегда',
    plain: 'обычная',
    differ: 'разные',
    again: 'снова',
    'again:': 'снова:',
    checks: 'проверок',

    // Песочница: сцена по умолчанию
    open: 'открыт',
    phase: 'фаза',
    unitX: 'юнитX',
    unitY: 'юнитY'
}

/**
 * Строки в кавычках: их печатают на табло, и по-английски они остались бы английскими.
 * Ключи словаря карты (`localeprint`) тоже здесь — там слово стоит именем ключа.
 */
export const STRINGS = {
    'all ': 'всего ',
    copper: 'медь',
    'copper colour: ': 'медь: ',
    'copper {0} of {1}': 'меди {0} из {1}',
    'stock ': 'запас ',
    ' of ': ' из ',
    needed: 'нужен',
    'done ': 'сделано ',
    loops: 'итераций',
    'loops ': 'итераций ',
    ', copper ': ', меди ',
    'in store ': 'на складе ',
    'loops: ': 'итераций: ',
    'copper: ': 'меди: ',
    enough: 'хватает',
    low: 'мало',
    'Wave incoming': 'Волна на подходе',
    'And one more': 'И ещё одна',
    alarm: 'тревога',
    'Alarm!': 'Тревога!',
    'task.drill': 'задача.бур',
    'task.nothing': 'задача.нетТакого',
    'task.done': 'задача.готово',
    'Build here': 'Строить здесь',
    'Hold the line!': 'Держите оборону!',
    'rain: ': 'дождь: ',
    'Build a drill': 'Постройте бур',
    'Task complete': 'Задача выполнена',

    // Песочница: табло и цели сцены по умолчанию
    'step: ': 'шаг: ',
    store: 'склад',
    '[accent]Hold out: []{0}': '[accent]Продержаться: []{0}',
    '[accent]Haul to the store: []10 copper': '[accent]Натаскать на склад: []10 меди'
}
