/**
 * Имена переменных в примерах — по-английски.
 *
 * Сцены пишутся один раз, по-русски: это настоящие программы, они гоняются тестами,
 * и держать две копии значило бы чинить каждую находку дважды. На английскую страницу
 * та же сцена приезжает с переписанными именами — как если бы её набрал англоязычный автор.
 *
 * Переписываются только **имена переменных и строковые литералы**. Сам язык не трогается:
 * `sensor`, `@copper`, `jump` и числа остаются как были — они и в русской версии английские.
 *
 * Словарь полный: тест `course.test.js` падает, если в сцене встретилось имя, которого
 * здесь нет. Иначе английский пример молча вышел бы наполовину русским.
 */

/** Имена переменных: русское имя из сцены — английское имя для страницы. */
export const NAMES = {
    // Основы: значения, имена, пустота
    запас: 'stock',
    Запас: 'Stock',
    запс: 'stok',
    расход: 'spend',
    предел: 'limit',
    итог: 'total',
    удвоено: 'doubled',
    копия: 'copy',
    число: 'number',
    текст: 'text',
    предмет: 'item',
    объектПлюсОдин: 'itemPlusOne',
    пусто: 'empty',
    пустое: 'blank',
    надпись: 'caption',
    значение: 'value',
    код: 'code',
    строка: 'row',
    столбец: 'column',

    // Арифметика и числа
    сумма: 'sum',
    разность: 'difference',
    произведение: 'product',
    частное: 'quotient',
    остаток: 'rest',
    разница: 'gap',
    доля: 'share',
    дробь: 'fraction',
    дробный: 'fractional',
    целое: 'whole',
    отрицательный: 'negative',
    почти: 'almost',
    точно: 'exact',
    сДопуском: 'withEpsilon',
    строго: 'strict',
    равно: 'same',
    оба: 'both',
    обе: 'either',
    инверт: 'flipped',
    маска: 'mask',
    сдвиг: 'shift',
    знак: 'sign',
    беззнак: 'unsigned',
    побитовое: 'bitwise',
    логическое: 'logical',
    безЕдиницы: 'lostBit',
    проверка: 'check',
    упаковано: 'packed',
    обратно: 'back',
    обратноX: 'backX',
    обратноY: 'backY',
    шаг: 'step',
    счёт: 'count',
    итераций: 'loops',
    итерацийЗаТик: 'loopsPerTick',
    холостых: 'idle',
    сработало: 'fired',
    срок: 'deadline',
    прежний: 'previous',
    другой: 'changed',
    смен: 'swaps',
    привязок: 'binds',
    перебор: 'wrapped',
    негоден: 'gone',
    сделано: 'done',
    готово: 'ready',
    пропущено: 'skipped',
    послеСтопа: 'afterStop',

    // Сравнения из урока про логику
    медьРавнаМеди: 'copperIsCopper',
    медьРавнаСвинцу: 'copperIsLead',
    пустоеРавноНулю: 'blankIsZero',
    пустоеСтрого: 'blankStrictly',
    безЗначения: 'unset',
    наНоль: 'byZero',
    хотяБы: 'atLeastOne',
    сОдной: 'withOne',

    // Время
    тики: 'ticks',
    секунды: 'seconds',
    минуты: 'minutes',
    миллисекунды: 'millis',
    изТиков: 'fromTicks',
    текущее: 'current',
    показов: 'frames',
    снимков: 'samples',

    // Память и связи
    адрес: 'address',
    ячейки: 'cells',
    памятьЯчейки: 'cellSize',
    памятьМаршрута: 'routerSize',
    блок: 'block',
    здание: 'building',
    здание2: 'building2',
    первый: 'first',
    второй: 'second',
    третий: 'third',
    четвёртый: 'fourth',
    первая: 'firstOne',
    вторая: 'secondOne',
    третья: 'thirdOne',
    первое: 'firstText',
    второе: 'secondText',
    новый: 'fresh',
    номер: 'index',
    номерГрафита: 'graphiteId',
    первыйПредмет: 'firstItem',
    перваяЖидкость: 'firstLiquid',
    первыйЮнит: 'firstUnit',
    заГраницей: 'pastEnd',
    предметов: 'itemCount',
    лучшее: 'best',
    чего: 'what',
    сколько: 'amount',
    сколькоБрать: 'howMany',
    всего: 'everything',
    хватает: 'enough',
    мало: 'low',
    много: 'plenty',
    осталось: 'left',

    // Содержимое складов
    медь: 'copper',
    меди: 'copperLeft',
    свинца: 'leadLeft',
    кремний: 'silicon',
    вода: 'water',
    медьВЯдре: 'copperInCore',
    медиНаСкладе: 'copperInStore',
    вСкладе: 'inStore',
    склад: 'store',
    складX: 'storeX',
    складY: 'storeY',
    ядро: 'core',
    естьСклад: 'storeFound',
    чужойСклад: 'enemyStore',
    привезено: 'delivered',
    выдать: 'give',

    // Блоки и настройка
    настройка: 'setting',
    включено: 'on',
    включили: 'switched',
    работает: 'running',
    свойРаботает: 'mineRuns',
    чужойРаботает: 'theirsRuns',
    свой: 'mine',
    чужой: 'theirs',
    своя: 'ours',
    вражья: 'enemys',
    свояX: 'oursX',
    свояY: 'oursY',
    своих: 'ourOwn',
    своихЗданий: 'ourBuildings',
    своихЮнитов: 'ourUnits',
    чужихЮнитов: 'theirUnits',
    врагов: 'enemies',
    турелей: 'turrets',
    команд: 'commands',
    команда: 'team',
    стена: 'wall',
    пол: 'floor',
    руда: 'ore',
    безРуды: 'noOre',
    рудаX: 'oreX',
    рудаY: 'oreY',
    поставил: 'placed',
    поставили: 'wasPlaced',
    гдеПоставили: 'wherePlaced',
    поТемЖеЧислам: 'sameNumbers',
    снесли: 'removed',
    взорвали: 'blown',
    подожгли: 'burned',
    подняли: 'lifted',
    нашлось: 'found',
    найдено: 'wasFound',
    нужен: 'needed',
    нужно: 'need',

    // Юниты
    юнит: 'unit',
    юнитов: 'unitCount',
    мой: 'own',
    тотЖе: 'sameOne',
    мёртв: 'dead',
    живых: 'alive',
    живучий: 'tough',
    здоровье: 'health',
    здоровьеТурели: 'turretHealth',
    ближнееЗдоровье: 'nearHealth',
    слабоеЗдоровье: 'weakHealth',
    тип: 'kind',
    типПервого: 'firstKind',
    типНового: 'newKind',
    метка: 'tag',
    помечено: 'tagged',
    последний: 'lastTag',
    груз: 'cargo',
    мест: 'slots',
    копает: 'mining',
    прибыл: 'arrived',
    дошли: 'reached',
    куда: 'target',
    летит: 'flies',
    летящий: 'flying',
    скорость: 'speed',
    разогнанная: 'boosted',
    кем: 'ctrl',
    кто: 'who',
    ктоЭто: 'whoIsIt',
    яСам: 'myself',
    чейКинжал: 'whoseDagger',
    отдал: 'ordered',
    кубик: 'roll',
    бросок: 'throw',

    // Поиск и радар
    ближний: 'near',
    дальний: 'far',
    слабый: 'weakest',
    ближе: 'closer',
    далеко: 'away',
    рядом: 'beside',
    дальность: 'range',
    расстояние: 'distance',
    вПрямоугольнике: 'inBox',
    естьВраг: 'enemyFound',
    естьСвоя: 'allyFound',
    врагX: 'enemyX',
    врагY: 'enemyY',
    битый: 'damaged',
    битыйX: 'damagedX',
    битыйY: 'damagedY',
    xБлижнего: 'nearX',
    xДальнего: 'farX',
    xСкованного: 'heldX',
    xСвободного: 'freeX',
    нетX: 'missX',
    нетY: 'missY',
    титанЕсть: 'titaniumFound',
    цель: 'aim',
    стреляет: 'shooting',
    патронов: 'ammo',
    выстрелов: 'shots',
    пуля: 'shot',
    поворот: 'facing',
    угол: 'angle',
    диагональ: 'diagonal',
    полное: 'full',
    вверх: 'up',
    вниз: 'down',
    назад: 'behind',
    после: 'after',
    тут: 'here',
    сам: 'self',

    // Цвет и рисование
    цвет: 'colour',
    красный: 'red',
    голубой: 'blue',
    кр: 'r',
    зел: 'g',
    син: 'b',
    прозр: 'a',
    тревога: 'alarm',
    покой: 'calm',

    // Мир и погода
    буря: 'storm',
    дождь: 'rain',
    высота: 'height',
    ошибка: 'failure',
    всегда: 'always',
    обычная: 'plain',
    разные: 'differ',
    снова: 'again',
    'снова:': 'again:',
    проверок: 'checks'
}

/**
 * Строки в кавычках: их печатают на табло, и по-русски они остались бы русскими.
 * Ключи словаря карты (`localeprint`) тоже здесь — там русское слово стоит именем ключа.
 */
export const STRINGS = {
    'всего ': 'all ',
    'медь': 'copper',
    'медь: ': 'copper: ',
    'меди {0} из {1}': 'copper {0} of {1}',
    'запас ': 'stock ',
    ' из ': ' of ',
    'нужен': 'needed',
    'сделано ': 'done ',
    'итераций': 'loops',
    'итераций ': 'loops ',
    ', меди ': ', copper ',
    'на складе ': 'in store ',
    'итераций: ': 'loops: ',
    'меди: ': 'copper: ',
    'хватает': 'enough',
    'мало': 'low',
    'Волна на подходе': 'Wave incoming',
    'И ещё одна': 'And one more',
    'тревога': 'alarm',
    'Тревога!': 'Alarm!',
    'задача.бур': 'task.drill',
    'задача.нетТакого': 'task.nothing',
    'задача.готово': 'task.done',
    'Строить здесь': 'Build here',
    'Держите оборону!': 'Hold the line!',
    'дождь: ': 'rain: ',
    'Постройте бур': 'Build a drill',
    'Задача выполнена': 'Task complete'
}
